// License: MIT
//
// Copyright (c) 2026 <your-organization>
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

import type { AgentState } from '../state/sessionTypes';
import type { EnvironmentState } from '../state/sessionTypes';
import type { ChatMessage } from '../state/sessionTypes';

/**
 * Error type used by the chat adapter.
 */
export class ChatError extends Error {
  public readonly name = 'ChatError';
  constructor(message: string) {
    super(message);
    this.name = 'ChatError';
  }
}

/**
 * Request payload for sending a chat message to the adapter.
 *
 * Required fields:
 * - sessionId: unique identifier for the current session
 * - userMessage: text content of the user's message
 * - agentState: current agent state (including displayName, personaPreset, etc.)
 * - environmentState: current environment state (including preset, lighting, etc.)
 * - recentMessages: array of recent chat messages in the session
 */
export interface ChatRequest {
  sessionId: string;
  userMessage: string;
  agentState: AgentState;
  environmentState: EnvironmentState;
  recentMessages: ChatMessage[];
}

/**
 * Response payload returned by a chat adapter.
 */
export interface ChatResponse {
  /** Text response generated by the adapter */
  response: string;
  /** Unique identifier for the new message */
  newMessageId: string;
}

/**
 * Chat adapter interface.
 *
 * The `send` method processes a request and returns a deterministic response.
 * In the MVP this is implemented by {@link mockChatAdapter}.
 */
export interface ChatAdapter {
  /**
   * Sends a chat request to the adapter.
   *
   * @param request - The chat request containing session and context information.
   * @param signal - Optional {@link AbortSignal} for request cancellation.
   * @returns A promise that resolves to a {@link ChatResponse}.
   *
   * @throws {@link ChatError} if required fields are missing or the request is aborted.
   */
  send(request: ChatRequest, signal?: AbortSignal): Promise<ChatResponse>;
}

/**
 * Deterministic mock chat adapter for the MVP.
 *
 * This implementation runs entirely in-browser, does not require any backend,
 * and returns deterministic responses that reference the agent's display name
 * and environment preset. It is safe for unit testing and does not mutate
 * external session state.
 */
export const mockChatAdapter: ChatAdapter = {
  async send(request, signal) {
    // Validate required fields
    if (!request.sessionId) {
      throw new ChatError('sessionId is required');
    }
    if (!request.userMessage) {
      throw new ChatError('userMessage is required');
    }
    if (!request.agentState) {
      throw new ChatError('agentState is required');
    }
    if (!request.environmentState) {
      throw new ChatError('environmentState is required');
    }
    if (!request.recentMessages) {
      throw new ChatError('recentMessages is required');
    }

    // Cancellation support
    if (signal?.aborted) {
      throw new ChatError('Request aborted');
    }

    // Extract context information
    const { displayName, personaPreset } = request.agentState;
    const { preset: environmentPreset } = request.environmentState;

    // Build a deterministic response using context information
    let response = [
      `Response from ${displayName} (${personaPreset})`,
      `Environment: ${environmentPreset}`,
    ].join(' ');

    // Optionally include snippet of recent user message for context
    const lastUserMessage = request.recentMessages
      .filter(msg => msg.sender === 'user')
      .pop()
      ?.content;
    if (lastUserMessage) {
      response += ` Context: "${lastUserMessage.substring(0, 30)}"`;
    }

    // Return deterministic response with stable message ID
    return {
      response,
      newMessageId: 'mock-message-id',
    };
  },
};